export const tableItems = [
	{
		index: 1,
		table: 'Stół I',
		guestList: [
			'Dominik Matras',
			'Gabriela Bagińska',
			'Kacper Kowalski',
			'Kamila Nowak',
			'Kamil Kowalczyk',
			'Karol Nowak',
			'Karolina Kowalczyk',
			'Katarzyna Nowak',
			'Klaudia Kowalczyk',
			'Krzysztof Nowak',
			'Kuba Kowalczyk',
			'Maciej Nowak',
			'Maja Kowalczyk',
			'Marek Nowak',
			'Maria Kowalczyk',
			'Mateusz Nowak',
			'Michał Kowalczyk',
		],
	},
	{
		index: 2,
		table: 'Stół II',
		guestList: [
			'Dominik Matras',
			'Gabriela Bagińska',
			'Kacper Kowalski',
			'Kamila Nowak',
			'Kamil Kowalczyk',
			'Karol Nowak',
			'Karolina Kowalczyk',
			'Katarzyna Nowak',
			'Klaudia Kowalczyk',
			'Krzysztof Nowak',
			'Kuba Kowalczyk',
			'Maciej Nowak',
			'Maja Kowalczyk',
			'Marek Nowak',
			'Maria Kowalczyk',
			'Mateusz Nowak',
			'Michał Kowalczyk',
		],
	},
	{
		index: 3,
		table: 'Stół III',
		guestList: [
			'Dominik Matras',
			'Gabriela Bagińska',
			'Kacper Kowalski',
			'Kamila Nowak',
			'Kamil Kowalczyk',
			'Karol Nowak',
			'Karolina Kowalczyk',
			'Katarzyna Nowak',
			'Klaudia Kowalczyk',
			'Krzysztof Nowak',
			'Kuba Kowalczyk',
			'Maciej Nowak',
			'Maja Kowalczyk',
			'Marek Nowak',
			'Maria Kowalczyk',
			'Mateusz Nowak',
			'Michał Kowalczyk',
		],
	},
]
